import type { ProductStageFact } from "./analytics-derived";
import type { AnalyticsInsight } from "./analytics-insights";
import type { AnalyticsV2Load } from "./analytics-v2-loader";
import {acquisitionLabel,comparisonText,confidenceLabel,contextLabel,lowDataMessage,lowDataState,orderInsights,percentChangeText} from "./analytics-v2-language";

const text=(v:unknown)=>String(v??"").trim(), rate=(n:number,d:number)=>d>0?n/d:null;

export type Metric={count:number;visitors:number;rate:number|null};
export type AnalyticsV2ViewModel=ReturnType<typeof buildAnalyticsV2ViewModel>;
const visitors=(facts:Array<{visitorId:string|null}>)=>new Set(facts.map(x=>x.visitorId).filter(Boolean)).size;
const opportunities=(facts:ProductStageFact[])=>new Set(facts.filter(f=>f.visitorId&&f.opportunity).map(f=>`${f.visitorId}:${f.product.key}:${f.opportunity!.stateId}:${f.opportunity!.position}`)).size;
const median=(xs:number[])=>{if(!xs.length)return null;const s=[...xs].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2};
const evidenceName=(name:string)=>({searches:"търсения",zero_result_rate:"дял без резултат",median_supply:"медианно предлагане",selection_rate:"дял отваряния",cohort_median:"медиана на сравнимата група",outbound_intent_rate:"дял преминавания към бранда",qualified_exposures:"реални показвания",outbound_intent_per_visitor:"преминавания към бранда на посетител",product_repeat_interest_rate:"повторен продуктов интерес",brand_repeat_interest_rate:"повторен интерес към бранд"} as Record<string,string>)[name]||name;
export function renderInsight(insight:AnalyticsInsight){const rawLabel=insight.subject.label||insight.subject.id,label=insight.subject.type==="surface"?contextLabel(rawLabel):rawLabel,percent=insight.magnitude.percent==null?null:Math.abs(insight.magnitude.percent),direction=(insight.magnitude.percent??0)>=0?"се увеличи":"намаля";let statement="Наблюдава се измерима промяна в поведението.",interpretation="Това е наблюдавана разлика в Българитъм и само по себе си не показва причината за промяната.";
 if(insight.subject.type==="search"&&insight.type==="trend")statement=`Търсенията за „${label}“ ${direction}ха с ${percent?.toFixed(1)}% спрямо предходния период.`;
 else if(insight.subject.type==="search")statement=insight.currentValue===0?`Търсенията за „${label}“ не върнаха резултати в наблюдаваната извадка.`:`Търсенията за „${label}“ имат ограничено налично предлагане.`;
 else if(insight.subject.type==="product"&&insight.type==="hidden_winner")statement=`Този продукт се показва по-рядко, но има по-висок дял отваряния от сравнимите продукти.`;
 else if(insight.subject.type==="product"&&insight.type==="underperformer")statement=`Този продукт има по-нисък дял отваряния от сравнимите продукти.`;
 else if(insight.subject.type==="surface"){statement=`Продуктите в „${label}“ са били показани ${direction==="се увеличи"?"по-често":"по-рядко"}.`;interpretation="Това показва промяна във видимостта, но само по показванията не можем да заключим дали интересът към продуктите също се е променил.";}
 else if(insight.subject.type==="acquisition")statement=`Посетителите от „${label}“ показаха по-силен измерен интерес към сайтовете на брандовете от сравнимите източници.`;
 else if(insight.subject.type.endsWith("_repeat"))statement=`Повторният ${insight.subject.type==="product_repeat"?"продуктов интерес":"интерес към бранд"} ${direction} спрямо предходния период.`;
 return{...insight,statement,interpretation,confidenceLabel:confidenceLabel(insight.confidence),comparison:comparisonText(insight.currentValue,insight.comparisonValue),change:percentChangeText(insight.currentValue,insight.comparisonValue),evidenceText:insight.evidence.map(e=>`${evidenceName(e.metric)}: ${new Intl.NumberFormat("bg-BG",{maximumFractionDigits:Number.isInteger(e.value)?0:1}).format(e.value)}`).join(" · "),sampleText:`${insight.sample.events} събития · ${insight.sample.visitors} посетители · ${insight.sample.opportunities} възможности`,caveat:insight.caveats.length?"Наблюдавано поведение на съгласили се анонимни браузъри; не доказва причинност.":"",question:insight.suggestedAction||"Проверете контекста и извадката преди решение."};}

export function buildAnalyticsV2ViewModel(load:AnalyticsV2Load){const d=load.current,events=load.currentEvents;
 const eligibleVisitors=new Set(d.eligibleProductOpportunities.map(x=>x.visitorId).filter(Boolean)).size,eligibleOpps=new Set(d.eligibleProductOpportunities.filter(x=>x.visitorId).map(x=>`${x.visitorId}:${x.product.key}:${x.stateId}:${x.position}`)).size,exposedOpps=opportunities(d.productExposures),selectedOpps=opportunities(d.productSelections),pageOpps=opportunities(d.productPageViews),consideredOpps=opportunities(d.productConsiderations),outboundOpps=opportunities(d.productOutboundIntents);
 const funnel=[{label:"Продукти, които са могли да бъдат показани",count:eligibleOpps,visitors:eligibleVisitors,rate:null},{label:"Реално показани продукти",count:d.productExposures.length,visitors:visitors(d.productExposures),rate:rate(exposedOpps,eligibleOpps)},{label:"Отворени след показване",count:d.productSelections.length,visitors:visitors(d.productSelections),rate:rate(selectedOpps,exposedOpps)},{label:"Прегледи на продуктови страници",count:d.productPageViews.length,visitors:visitors(d.productPageViews),rate:rate(pageOpps,selectedOpps)},{label:"Сигнали за интерес",count:d.productConsiderations.length,visitors:visitors(d.productConsiderations),rate:rate(consideredOpps,pageOpps)},{label:"Преминавания към сайтовете на брандовете",count:d.productOutboundIntents.length,visitors:visitors(d.productOutboundIntents),rate:rate(outboundOpps,pageOpps),secondaryRate:rate(outboundOpps,exposedOpps)}];
 const qmap=new Map<string,typeof d.searchEpisodes>();for(const e of d.searchEpisodes){const q=text(e.query).normalize("NFKC").toLocaleLowerCase("bg");if(q)qmap.set(q,[...(qmap.get(q)||[]),e])}const searches=[...qmap].map(([query,es])=>({query,searches:es.length,visitors:new Set(es.map(e=>e.visitorId).filter(Boolean)).size,zero:es.filter(e=>e.resultCount===0).length,zeroRate:rate(es.filter(e=>e.resultCount===0).length,es.length),reformulations:es.filter(e=>e.reformulationCandidate).length,reformulationRate:rate(es.filter(e=>e.reformulationCandidate).length,es.length),medianSupply:median(es.map(e=>e.resultCount)),exposed:es.reduce((n,e)=>n+e.exposed,0),selected:es.reduce((n,e)=>n+e.selected,0),outbound:es.reduce((n,e)=>n+e.outbound,0),selectionRate:rate(es.filter(e=>e.selected>0).length,es.length),outboundRate:rate(es.filter(e=>e.outbound>0).length,es.length)})).sort((a,b)=>b.searches-a.searches||a.query.localeCompare(b.query,"bg"));
 const labelFor=(key:string,kind:"product"|"brand")=>{const facts=[...d.productExposures,...d.productSelections,...d.productPageViews,...d.productConsiderations,...d.productOutboundIntents,...d.brandQualifiedImpressions,...d.brandSelections,...d.brandPageViews,...d.brandOutboundIntents];const e=facts.find(f=>kind==="product"?f.product.key===key:f.brand?.key===key)?.event;return kind==="product"?{name:e?.productName||e?.productSlug||key,brand:e?.brandName||e?.brandSlug||"—"}:{name:e?.brandName||e?.brandSlug||key}};
 const products=d.productFunnel.map(r=>{const pos=d.eligibleProductOpportunities.filter(x=>x.product.key===r.product.key).map(x=>x.position);return{key:r.product.key,...labelFor(r.product.key,"product"),eligible:r.eligible.uniqueProductOpportunities,exposed:r.exposed.uniqueProductOpportunities,visitors:r.exposed.uniqueVisitors,selected:r.selected.uniqueProductOpportunities,selectionRate:r.selectionPerExposure,pageViews:r.pageViewed.eventCount,consideration:r.considered.eventCount,outbound:r.outbound.eventCount,outboundRate:r.outboundPerExposure,medianPosition:median(pos),surfaces:[...new Set(d.productExposures.filter(x=>x.product.key===r.product.key).map(x=>x.sourceSurface).filter(Boolean))].join(", ")||"—"}}).sort((a,b)=>b.exposed-a.exposed||a.key.localeCompare(b.key));
 const brandKeys=new Set([...d.brandQualifiedImpressions,...d.brandSelections,...d.brandPageViews,...d.brandOutboundIntents,...d.productExposures].map(f=>f.brand?.key).filter(Boolean) as string[]),brands=[...brandKeys].map(key=>{const direct=(xs:ProductStageFact[])=>xs.filter(x=>x.brand?.key===key),journeys=d.brandJourneyFacts.filter(x=>x.brand.key===key);return{key,...labelFor(key,"brand"),impressions:direct(d.brandQualifiedImpressions).length,selections:direct(d.brandSelections).length,pageViews:direct(d.brandPageViews).length,outbound:direct(d.brandOutboundIntents).length,multiProduct:d.brandMultiProductExploration.filter(x=>x.brand.key===key).length,repeatVisitors:new Set(d.brandRepeatInterest.filter(x=>x.brand?.key===key).map(x=>x.visitorId)).size,productExposures:direct(d.productExposures).length,productSelections:direct(d.productSelections).length,productOutbound:direct(d.productOutboundIntents).length,visitors:new Set(journeys.map(x=>x.visitorId)).size}}).sort((a,b)=>b.productExposures-a.productExposures||a.key.localeCompare(b.key));
 const canonical=new Set(d.discoveryOpportunities.map(x=>x.surface_type)),surfaces=d.surfaces.map(s=>({...s,label:contextLabel(s.surface),canonical:canonical.has(s.surface),eligible:canonical.has(s.surface)?s.eligible:null,selectionRate:rate(s.selected,s.exposed)})).sort((a,b)=>b.exposed-a.exposed);
 const aq=new Map<string,{source:string;medium:string;campaign:string;referrer:string;visitorIds:Set<string>;sessionIds:Set<string>;discoverySessions:Set<string>;exposed:number;selected:number;considered:number;outbound:number;returning:Set<string>}>(),acq=(e:(typeof events)[number])=>{const source=e.utmSource||e.acquisitionChannel||"direct",key=[source,e.utmMedium,e.utmCampaign,e.referrerDomain].join("|");return{key,row:aq.get(key)||{source,medium:e.utmMedium,campaign:e.utmCampaign,referrer:e.referrerDomain,visitorIds:new Set<string>(),sessionIds:new Set<string>(),discoverySessions:new Set<string>(),exposed:0,selected:0,considered:0,outbound:0,returning:new Set<string>()}}};for(const e of events){const{key,row}=acq(e);if(e.journeyId)row.visitorIds.add(e.journeyId);if(e.sessionId){row.sessionIds.add(e.sessionId);if(d.sessions.find(s=>s.id===e.sessionId)?.discoveryActive)row.discoverySessions.add(e.sessionId)}if(e.journeyId&&d.visitors.find(v=>v.id===e.journeyId)?.returning)row.returning.add(e.journeyId);aq.set(key,row)}const touch=(f:ProductStageFact,k:"exposed"|"selected"|"considered"|"outbound")=>{const{key,row}=acq(f.event);row[k]++;aq.set(key,row)};d.productExposures.forEach(f=>touch(f,"exposed"));d.productSelections.forEach(f=>touch(f,"selected"));d.productConsiderations.forEach(f=>touch(f,"considered"));d.productOutboundIntents.forEach(f=>touch(f,"outbound"));const acquisition=[...aq.values()].filter(x=>x.visitorIds.size>=2).map(x=>({...x,visitors:x.visitorIds.size,sessions:x.sessionIds.size,discoveryActiveSessions:x.discoverySessions.size,returningVisitors:x.returning.size})).sort((a,b)=>b.visitors-a.visitors);
 const orderedInsights=orderInsights(load.insights),state=lowDataState({events:events.length,insights:orderedInsights.length,comparisonAvailable:load.meta.comparisonAvailable}),classifiedAcquisition=acquisition.map(x=>({...x,channelLabel:acquisitionLabel(x)})),unknownGroups=classifiedAcquisition.filter(x=>x.channelLabel==="Неопределен източник"),unknownVisits=unknownGroups.reduce((sum,x)=>sum+x.sessions,0),unknownReasons=[{label:"посещения без достатъчна информация за източника",count:unknownGroups.filter(x=>!text(x.referrer)&&(!text(x.source)||["unknown","legacy"].includes(text(x.source).toLowerCase()))&&!text(x.medium)).reduce((sum,x)=>sum+x.sessions,0)},{label:"посещения с неразпознати стойности за източник",count:unknownGroups.filter(x=>Boolean(text(x.referrer)||text(x.medium)||!["","unknown","legacy"].includes(text(x.source).toLowerCase()))).reduce((sum,x)=>sum+x.sessions,0)}].filter(x=>x.count>0);
 const returningVisitors=d.summary.returningAnonymousVisitors,overviewFacts=[{key:"visitors",label:"Разпознати анонимни браузъри",value:d.summary.uniqueVisitors},{key:"searches",label:"Търсения",value:d.searchEpisodes.length},{key:"selections",label:"Отваряния на продукти",value:d.productSelections.length},{key:"pageViews",label:"Прегледи на продуктови страници",value:d.productPageViews.length},{key:"outbound",label:"Преминавания към сайтове на брандове",value:d.productOutboundIntents.length},{key:"returning",label:"Браузъри с повторен интерес",value:returningVisitors}];
 const browserCount=d.summary.uniqueVisitors,browserWord=browserCount===1?"разпознат анонимен браузър":"разпознати анонимни браузъра";
 return{period:load.meta,insights:orderedInsights.map(renderInsight),overview:{summary:browserCount?`През периода има активност от ${browserCount} ${browserWord}.`:"През периода няма измерена активност от разпознати анонимни браузъри.",facts:overviewFacts},lowData:{state,message:lowDataMessage(state)},funnel,search:{searches,totals:{searches:d.searchEpisodes.length,visitors:new Set(d.searchEpisodes.map(e=>e.visitorId).filter(Boolean)).size,zero:d.searchEpisodes.filter(e=>e.resultCount===0).length,zeroRate:rate(d.searchEpisodes.filter(e=>e.resultCount===0).length,d.searchEpisodes.length),reformulationRate:rate(d.searchEpisodes.filter(e=>e.reformulationCandidate).length,d.searchEpisodes.length),selectionRate:rate(d.searchEpisodes.filter(e=>e.selected>0).length,d.searchEpisodes.length),outboundRate:rate(d.searchEpisodes.filter(e=>e.outbound>0).length,d.searchEpisodes.length)}},surfaces,products,brands,returning:{visitors:browserCount,returning:returningVisitors,rate:rate(returningVisitors,browserCount),repeatProducts:new Set(d.productRepeatInterest.map(x=>x.visitorId)).size,repeatBrands:new Set(d.brandRepeatInterest.map(x=>x.visitorId)).size},acquisition:classifiedAcquisition,acquisitionUnknown:{visits:unknownVisits,reasons:unknownReasons},quality:{events:events.length,completeStates:d.summary.completeDiscoveryOpportunities,incompleteStates:d.summary.incompleteDiscoveryOpportunities,members:d.discoveryMembers.length,legacyViews:d.legacyUndifferentiatedProductViews.length,missingIdentity:events.filter(e=>!text(e.journeyId)).length,comparisonAvailable:load.meta.comparisonAvailable,lookbackAvailable:load.meta.lookbackAvailable,diagnostics:d.discoveryDiagnostics.length}};
}
