import type {DerivedAnalyticsDomain,ProductIdentity} from "./analytics-derived";
export type InsightType="trend"|"anomaly"|"opportunity"|"hidden_winner"|"underperformer"|"friction"|"behavior_change"|"acquisition_quality";
export type InsightConfidence="LOW"|"MEDIUM"|"HIGH";
export type AnalyticsInsight={type:InsightType;subject:{type:"search"|"product"|"surface"|"acquisition"|"product_repeat"|"brand_repeat";id:string;label?:string};statement:string;currentValue:number;comparisonValue:number|null;magnitude:{absolute:number|null;percent:number|null};sample:{events:number;visitors:number;opportunities:number;cohortSize?:number;comparisonSample?:number};confidence:InsightConfidence;evidence:Array<{metric:string;value:number;unit?:string}>;caveats:string[];suggestedAction?:string;drilldown:Record<string,string|number|boolean|null>};
export type ProductInsightMetric={product:ProductIdentity;eligible:number;exposed:number;selected:number;outbound:number;visitors:number;productType:string;category:string;subcategory:string;surface:string;positionBand:string};
export type SearchInsightMetric={query:string;searches:number;zeroResults:number;medianSupply:number;exposed:number;selected:number;considered:number;outbound:number;visitors:number};
export type SurfaceInsightMetric={surface:string;eligible:number;exposures:number;selections:number;visitors:number};
export type AcquisitionInsightMetric={source:string;visitors:number;exposures:number;selections:number;considerations:number;outbound:number};
export type InsightPeriodSnapshot={label:string;products:ProductInsightMetric[];searches:SearchInsightMetric[];surfaces:SurfaceInsightMetric[];acquisition:AcquisitionInsightMetric[];repeatInterest:{productVisitors:number;brandVisitors:number;eligibleVisitors:number}};
export type InsightEngineConfig={minimumSample:number;minimumOpportunities:number;minimumVisitors:number;minimumCohortSize:number;mediumSample:number;highSample:number;materialPercentChange:number;thinSupplyMax:number;rateLift:number};
export const DEFAULT_INSIGHT_CONFIG:InsightEngineConfig={minimumSample:20,minimumOpportunities:20,minimumVisitors:10,minimumCohortSize:5,mediumSample:50,highSample:200,materialPercentChange:20,thinSupplyMax:3,rateLift:.25};
export const safeRate=(n:number,d:number)=>d>0?n/d:null,absoluteChange=(a:number,b:number)=>a-b,percentageChange=(a:number,b:number)=>b===0?null:(a-b)/b*100;
export const median=(vs:number[])=>{if(!vs.length)return null;const s=[...vs].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2};
export const quantile=(vs:number[],q:number)=>{if(!vs.length)return null;const s=[...vs].sort((a,b)=>a-b),p=(s.length-1)*Math.max(0,Math.min(1,q)),l=Math.floor(p),u=Math.ceil(p);return s[l]*(1-(p-l))+s[u]*(p-l)};
export const quartiles=(vs:number[])=>({q1:quantile(vs,.25),median:quantile(vs,.5),q3:quantile(vs,.75)}),percentile=(v:number,vs:number[])=>vs.length?vs.filter(x=>x<=v).length/vs.length:null;
export type ConfidenceEvidence={subjectSample:number;opportunities:number;uniqueVisitors:number;cohortSize?:number;comparisonSample?:number};
export function confidenceFor(e:ConfidenceEvidence,c=DEFAULT_INSIGHT_CONFIG,requires:{cohort?:boolean;comparison?:boolean}={}):InsightConfidence|null{if(e.subjectSample<c.minimumSample||e.opportunities<c.minimumOpportunities||e.uniqueVisitors<c.minimumVisitors)return null;if(requires.cohort&&(e.cohortSize??0)<c.minimumCohortSize)return null;if(requires.comparison&&(e.comparisonSample??0)<c.minimumSample)return null;return e.subjectSample>=c.highSample&&e.opportunities>=c.highSample&&e.uniqueVisitors>=c.mediumSample?"HIGH":e.subjectSample>=c.mediumSample&&e.opportunities>=c.mediumSample?"MEDIUM":"LOW"}
const normalizeQuery=(q:string)=>q.normalize("NFKC").trim().replace(/\s+/g," ").toLocaleLowerCase("bg");
export type ProductCohort={peers:ProductInsightMetric[];definition:string;fallbackLevel:number};
export function constructProductCohort(subject:ProductInsightMetric,all:ProductInsightMetric[],minimum=DEFAULT_INSIGHT_CONFIG.minimumCohortSize):ProductCohort|null{const candidates:Array<[string,(x:ProductInsightMetric)=>boolean]>=[
 ["same product type + surface + position band",x=>Boolean(subject.productType)&&x.productType===subject.productType&&x.surface===subject.surface&&x.positionBand===subject.positionBand],
 ["same product type + surface",x=>Boolean(subject.productType)&&x.productType===subject.productType&&x.surface===subject.surface],
 ["same subcategory + surface",x=>Boolean(subject.subcategory)&&x.subcategory===subject.subcategory&&x.surface===subject.surface],
 ["same category + surface",x=>Boolean(subject.category)&&x.category===subject.category&&x.surface===subject.surface],
 ["same product type",x=>Boolean(subject.productType)&&x.productType===subject.productType],
 ];for(let i=0;i<candidates.length;i++){const peers=all.filter(x=>x.product.key!==subject.product.key&&candidates[i][1](x));if(peers.length>=minimum)return{peers,definition:candidates[i][0],fallbackLevel:i}}return null}
export function buildInsightSnapshot(d:DerivedAnalyticsDomain,label:string):InsightPeriodSnapshot{const products=d.productFunnel.map(r=>({product:r.product,eligible:r.eligible.uniqueProductOpportunities,exposed:r.exposed.uniqueProductOpportunities,selected:r.selected.uniqueProductOpportunities,outbound:r.outbound.uniqueProductOpportunities,visitors:r.exposed.uniqueVisitors,productType:r.productType,category:r.category,subcategory:r.subcategory,surface:r.primarySurface,positionBand:r.positionBand}));const qm=new Map<string,typeof d.searchEpisodes>();for(const e of d.searchEpisodes){const k=normalizeQuery(e.query);qm.set(k,[...(qm.get(k)||[]),e])}const searches=[...qm].map(([query,es])=>({query,searches:es.length,zeroResults:es.filter(e=>e.resultCount===0).length,medianSupply:median(es.map(e=>e.resultCount))||0,exposed:es.reduce((n,e)=>n+e.exposed,0),selected:es.reduce((n,e)=>n+e.selected,0),considered:es.reduce((n,e)=>n+e.considered,0),outbound:es.reduce((n,e)=>n+e.outbound,0),visitors:new Set(es.map(e=>e.visitorId).filter(Boolean)).size}));const surfaces=d.surfaces.map(s=>({surface:s.surface,eligible:s.eligible,exposures:s.exposed,selections:s.selected,visitors:s.uniqueVisitors}));const am=new Map<string,{visitors:Set<string>;exposures:number;selections:number;considerations:number;outbound:number}>(),add=(fs:typeof d.productExposures,k:"exposures"|"selections"|"considerations"|"outbound")=>fs.forEach(f=>{const source=f.event.acquisitionChannel||"unknown",r=am.get(source)||{visitors:new Set<string>(),exposures:0,selections:0,considerations:0,outbound:0};if(f.visitorId)r.visitors.add(f.visitorId);r[k]++;am.set(source,r)});add(d.productExposures,"exposures");add(d.productSelections,"selections");add(d.productConsiderations,"considerations");add(d.productOutboundIntents,"outbound");const acquisition=[...am].map(([source,r])=>({source,visitors:r.visitors.size,exposures:r.exposures,selections:r.selections,considerations:r.considerations,outbound:r.outbound}));return{label,products,searches,surfaces,acquisition,repeatInterest:{productVisitors:new Set(d.productRepeatInterest.map(x=>x.visitorId)).size,brandVisitors:new Set(d.brandRepeatInterest.map(x=>x.visitorId)).size,eligibleVisitors:d.summary.uniqueVisitors}}}
const mag=(a:number,b:number|null)=>({absolute:b==null?null:a-b,percent:b==null?null:percentageChange(a,b)}),baseCaveat="Observed behavior among consenting Bulgaritam browsers; correlation does not establish causality.";
export function generateAnalyticsInsights(cur:InsightPeriodSnapshot,prev:InsightPeriodSnapshot,c=DEFAULT_INSIGHT_CONFIG){const out:AnalyticsInsight[]=[],add=(x:AnalyticsInsight)=>out.push(x),sample=(events:number,visitors:number,opportunities:number,cohortSize?:number,comparisonSample?:number)=>({events,visitors,opportunities,cohortSize,comparisonSample});
 for(const r of cur.searches){const old=prev.searches.find(x=>x.query===r.query),ev={subjectSample:r.searches,opportunities:r.searches,uniqueVisitors:r.visitors,comparisonSample:old?.searches};if(old){const change=percentageChange(r.searches,old.searches),conf=confidenceFor(ev,c,{comparison:true});if(conf&&change!=null&&Math.abs(change)>=c.materialPercentChange)add({type:"trend",subject:{type:"search",id:r.query,label:r.query},statement:`Search activity for “${r.query}” changed ${Math.abs(change).toFixed(1)}% versus the previous equivalent period among Bulgaritam users.`,currentValue:r.searches,comparisonValue:old.searches,magnitude:mag(r.searches,old.searches),sample:sample(r.searches,r.visitors,r.searches,undefined,old.searches),confidence:conf,evidence:[{metric:"searches",value:r.searches}],caveats:[baseCaveat],drilldown:{query:r.query}})}const conf=confidenceFor(ev,c);const zeroRate=safeRate(r.zeroResults,r.searches);if(conf&&((zeroRate===1)||(r.medianSupply>0&&r.medianSupply<=c.thinSupplyMax)))add({type:"opportunity",subject:{type:"search",id:r.query,label:r.query},statement:zeroRate===1?`All observed searches for “${r.query}” produced zero results on Bulgaritam.`:`Searches for “${r.query}” had a thin observed median result set.`,currentValue:r.medianSupply,comparisonValue:null,magnitude:mag(r.medianSupply,null),sample:sample(r.searches,r.visitors,r.searches),confidence:conf,evidence:[{metric:"zero_result_rate",value:zeroRate||0},{metric:"median_supply",value:r.medianSupply}],caveats:[baseCaveat,"Thin-supply threshold is provisional and configurable."],drilldown:{query:r.query}})}
 for(const r of cur.products){const cohort=constructProductCohort(r,cur.products,c.minimumCohortSize);if(!cohort)continue;const rate=safeRate(r.selected,r.exposed),rates=cohort.peers.map(x=>safeRate(x.selected,x.exposed)).filter((x):x is number=>x!=null),med=median(rates),conf=confidenceFor({subjectSample:r.exposed,opportunities:r.eligible,uniqueVisitors:r.visitors,cohortSize:cohort.peers.length},c,{cohort:true});if(!conf||rate==null||med==null)continue;const common={subject:{type:"product" as const,id:r.product.key},sample:sample(r.exposed,r.visitors,r.eligible,cohort.peers.length),confidence:conf,caveats:[baseCaveat],drilldown:{cohort:cohort.definition,fallback_level:cohort.fallbackLevel,percentile:percentile(rate,rates)}};if(rate<med*(1-c.rateLift))add({type:"underperformer",...common,statement:`This product's observed selection rate was below its comparable cohort median.`,currentValue:rate,comparisonValue:med,magnitude:mag(rate,med),evidence:[{metric:"selection_rate",value:rate},{metric:"cohort_median",value:med}],suggestedAction:"Review comparable card presentation and position context."});if(r.exposed<median(cohort.peers.map(x=>x.exposed))!&&rate>med*(1+c.rateLift))add({type:"hidden_winner",...common,statement:`This product had lower observed exposure and a stronger selection rate than its comparable cohort median.`,currentValue:rate,comparisonValue:med,magnitude:mag(rate,med),evidence:[{metric:"selection_rate",value:rate},{metric:"cohort_median",value:med}],suggestedAction:"Test more comparable exposure."});const or=safeRate(r.outbound,r.exposed),om=median(cohort.peers.map(x=>safeRate(x.outbound,x.exposed)).filter((x):x is number=>x!=null));if(or!=null&&om!=null&&r.outbound>=c.minimumSample&&or>om*(1+c.rateLift))add({type:"trend",...common,statement:`This product's observed outbound-intent rate was above its comparable cohort median.`,currentValue:or,comparisonValue:om,magnitude:mag(or,om),evidence:[{metric:"outbound_intent_rate",value:or},{metric:"cohort_median",value:om}]})}
 for(const r of cur.surfaces){const old=prev.surfaces.find(x=>x.surface===r.surface);if(!old)continue;const conf=confidenceFor({subjectSample:r.exposures,opportunities:r.eligible||r.exposures,uniqueVisitors:r.visitors,comparisonSample:old.exposures},c,{comparison:true}),change=percentageChange(r.exposures,old.exposures);if(conf&&change!=null&&Math.abs(change)>=c.materialPercentChange)add({type:"behavior_change",subject:{type:"surface",id:r.surface},statement:`Qualified exposure on ${r.surface} changed versus the previous equivalent period.`,currentValue:r.exposures,comparisonValue:old.exposures,magnitude:mag(r.exposures,old.exposures),sample:sample(r.exposures,r.visitors,r.eligible||r.exposures,undefined,old.exposures),confidence:conf,evidence:[{metric:"qualified_exposures",value:r.exposures}],caveats:[baseCaveat],drilldown:{surface:r.surface}})}
 for(const r of cur.acquisition){const peers=cur.acquisition.filter(x=>x.source!==r.source),med=median(peers.map(x=>safeRate(x.outbound,x.visitors)).filter((x):x is number=>x!=null)),rate=safeRate(r.outbound,r.visitors),conf=confidenceFor({subjectSample:r.visitors,opportunities:r.visitors,uniqueVisitors:r.visitors,cohortSize:peers.length},c,{cohort:true});if(conf&&rate!=null&&med!=null&&r.outbound>=c.minimumSample&&rate>med*(1+c.rateLift))add({type:"acquisition_quality",subject:{type:"acquisition",id:r.source},statement:`Visitors from ${r.source} showed higher observed outbound intent than the comparable acquisition-source median.`,currentValue:rate,comparisonValue:med,magnitude:mag(rate,med),sample:sample(r.outbound,r.visitors,r.visitors,peers.length),confidence:conf,evidence:[{metric:"outbound_intent_per_visitor",value:rate}],caveats:[baseCaveat],drilldown:{source:r.source}})}
 for(const kind of ["product","brand"] as const){const cv=kind==="product"?cur.repeatInterest.productVisitors:cur.repeatInterest.brandVisitors,pv=kind==="product"?prev.repeatInterest.productVisitors:prev.repeatInterest.brandVisitors,cr=safeRate(cv,cur.repeatInterest.eligibleVisitors),pr=safeRate(pv,prev.repeatInterest.eligibleVisitors),conf=confidenceFor({subjectSample:cv,opportunities:cur.repeatInterest.eligibleVisitors,uniqueVisitors:cv,comparisonSample:pv},c,{comparison:true}),change=cr!=null&&pr!=null?percentageChange(cr,pr):null;if(conf&&change!=null&&Math.abs(change)>=c.materialPercentChange)add({type:"behavior_change",subject:{type:kind==="product"?"product_repeat":"brand_repeat",id:`${kind}-repeat-interest`},statement:`Cross-session ${kind} repeat-interest rate changed versus the previous equivalent period.`,currentValue:cr!,comparisonValue:pr!,magnitude:mag(cr!,pr!),sample:sample(cv,cur.repeatInterest.eligibleVisitors,cur.repeatInterest.eligibleVisitors,undefined,pv),confidence:conf,evidence:[{metric:`${kind}_repeat_interest_rate`,value:cr!}],caveats:[baseCaveat,"Identity is anonymous-browser scoped and does not cross devices."],drilldown:{kind}})}return out}
