import type {DerivedAnalyticsDomain,ProductStageFact,SearchEpisode} from "./analytics-derived";
import {DEFAULT_INSIGHT_CONFIG} from "./analytics-insights";

const normalize=(value:unknown)=>String(value??"").normalize("NFKC").trim().replace(/\s+/g," ").toLocaleLowerCase("bg");
const rate=(numerator:number,denominator:number)=>denominator>0?numerator/denominator:null;
const median=(values:number[])=>{if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b),middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]:(sorted[middle-1]+sorted[middle])/2};
const directForEpisode=(fact:ProductStageFact,episode:SearchEpisode)=>fact.sessionId===episode.sessionId&&Boolean(fact.searchId&&episode.searchId&&fact.searchId===episode.searchId||fact.opportunity&&episode.states.some(state=>state.discovery_state_id===fact.opportunity!.stateId));
const countProducts=(facts:ProductStageFact[])=>[...new Map(facts.map(fact=>[fact.product.key,{key:fact.product.key,name:fact.event.productName||fact.event.productSlug||fact.product.key,brand:fact.event.brandName||fact.event.brandSlug||"—",count:0}])).values()].map(item=>({...item,count:facts.filter(fact=>fact.product.key===item.key).length})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,"bg")||a.key.localeCompare(b.key));
const countBrands=(facts:ProductStageFact[])=>[...new Map(facts.filter(fact=>fact.brand).map(fact=>[fact.brand!.key,{key:fact.brand!.key,name:fact.event.brandName||fact.event.brandSlug||fact.brand!.key,count:0}])).values()].map(item=>({...item,count:facts.filter(fact=>fact.brand?.key===item.key).length})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,"bg")||a.key.localeCompare(b.key));

export type SearchAttention={kind:"zero"|"limited"|"reformulation";query?:string;searches:number;visitors:number;medianResults?:number;reformulations?:number};

export function buildSearchPresentation(domain:DerivedAnalyticsDomain){
 const groups=new Map<string,SearchEpisode[]>();for(const episode of domain.searchEpisodes){const query=normalize(episode.query);if(query)groups.set(query,[...(groups.get(query)||[]),episode])}
 const searches=[...groups].map(([query,episodes])=>{const results=episodes.map(episode=>episode.resultCount),directSelections=domain.productSelections.filter(fact=>episodes.some(episode=>directForEpisode(fact,episode))),directOutbound=domain.productOutboundIntents.filter(fact=>episodes.some(episode=>directForEpisode(fact,episode)));return{query,searches:episodes.length,visitors:new Set(episodes.map(episode=>episode.visitorId).filter(Boolean)).size,zero:episodes.filter(episode=>episode.resultCount===0).length,zeroRate:rate(episodes.filter(episode=>episode.resultCount===0).length,episodes.length),limited:episodes.filter(episode=>episode.resultCount>0&&episode.resultCount<=DEFAULT_INSIGHT_CONFIG.thinSupplyMax).length,reformulations:episodes.filter(episode=>episode.reformulationCandidate).length,reformulationRate:rate(episodes.filter(episode=>episode.reformulationCandidate).length,episodes.length),medianSupply:median(results),minimumSupply:Math.min(...results),maximumSupply:Math.max(...results),exposed:episodes.reduce((sum,episode)=>sum+episode.exposed,0),selected:episodes.reduce((sum,episode)=>sum+episode.selected,0),considered:episodes.reduce((sum,episode)=>sum+episode.considered,0),outbound:episodes.reduce((sum,episode)=>sum+episode.outbound,0),selectionRate:rate(episodes.filter(episode=>episode.selected>0).length,episodes.length),outboundRate:rate(episodes.filter(episode=>episode.outbound>0).length,episodes.length),products:countProducts(directSelections),brands:countBrands(directOutbound)}}).sort((a,b)=>b.searches-a.searches||a.query.localeCompare(b.query,"bg"));
 const totals={searches:domain.searchEpisodes.length,visitors:new Set(domain.searchEpisodes.map(episode=>episode.visitorId).filter(Boolean)).size,zero:domain.searchEpisodes.filter(episode=>episode.resultCount===0).length,limited:domain.searchEpisodes.filter(episode=>episode.resultCount>0&&episode.resultCount<=DEFAULT_INSIGHT_CONFIG.thinSupplyMax).length,reformulations:domain.searchEpisodes.filter(episode=>episode.reformulationCandidate).length,reformulationRate:rate(domain.searchEpisodes.filter(episode=>episode.reformulationCandidate).length,domain.searchEpisodes.length),selectionRate:rate(domain.searchEpisodes.filter(episode=>episode.selected>0).length,domain.searchEpisodes.length),outboundRate:rate(domain.searchEpisodes.filter(episode=>episode.outbound>0).length,domain.searchEpisodes.length)};
 const eligible=(searches:number,visitors:number)=>searches>=DEFAULT_INSIGHT_CONFIG.minimumSample&&visitors>=DEFAULT_INSIGHT_CONFIG.minimumVisitors,attention:SearchAttention[]=[];
 for(const row of searches){if(!eligible(row.searches,row.visitors))continue;if(row.zero===row.searches)attention.push({kind:"zero",query:row.query,searches:row.searches,visitors:row.visitors});else if(row.medianSupply!=null&&row.medianSupply>0&&row.medianSupply<=DEFAULT_INSIGHT_CONFIG.thinSupplyMax)attention.push({kind:"limited",query:row.query,searches:row.searches,visitors:row.visitors,medianResults:row.medianSupply})}
 if(eligible(totals.searches,totals.visitors)&&totals.reformulations>0)attention.push({kind:"reformulation",searches:totals.searches,visitors:totals.visitors,reformulations:totals.reformulations});
 const priority={zero:0,limited:1,reformulation:2};attention.sort((a,b)=>priority[a.kind]-priority[b.kind]||b.searches-a.searches||(a.query||"").localeCompare(b.query||"","bg"));
 return{searches,totals,attention,thresholds:{minimumSample:DEFAULT_INSIGHT_CONFIG.minimumSample,minimumVisitors:DEFAULT_INSIGHT_CONFIG.minimumVisitors,limitedChoiceMax:DEFAULT_INSIGHT_CONFIG.thinSupplyMax}};
}
