const grid=document.querySelector<HTMLElement>("#dealGrid");
if(grid){
 let cards=Array.from(grid.querySelectorAll<HTMLElement>("[data-masonry-card]"));let limit=24;let eligible:any[]=[];
 const search=document.querySelector<HTMLInputElement>("#dealSearch"),sort=document.querySelector<HTMLSelectElement>("#dealSort"),modal=document.querySelector<HTMLElement>("#filtersModal"),count=document.querySelector<HTMLElement>("#resultCount"),empty=document.querySelector<HTMLElement>("#noResults"),badge=document.querySelector<HTMLElement>("#filterBadge"),toggle=document.querySelector<HTMLElement>("#filtersToggle");
 const split=(value?:string)=>(value||"").split("|").filter(Boolean);
 const mapItems=()=>cards.map((card,recommended)=>({card,recommended,category:card.dataset.dealCategory||card.querySelector<HTMLElement>("[data-deal-category-value]")?.dataset.dealCategoryValue||"",brand:card.dataset.brandId,discount:Number(card.dataset.discountPercent),price:Number(card.dataset.currentPrice),checked:Date.parse(card.dataset.checkedAt||""),search:card.dataset.search||"",materials:split(card.dataset.materials),ingredients:split(card.dataset.ingredients)}));
 let items=mapItems();const checked=(name:string)=>Array.from(modal?.querySelectorAll<HTMLInputElement>(`input[name="${name}"]:checked`)||[]).map((input)=>input.value);
 const bucket=(value:number,kind:string)=>kind==="discount"?(value<20?"under20":value<30?"20-30":value<=50?"30-50":"over50"):(value<25?"under25":value<50?"25-50":value<=100?"50-100":"over100");
 const state=()=>({query:search?.value.trim().toLocaleLowerCase("bg")||"",categories:checked("category"),brands:checked("brand"),discount:checked("discount")[0]||"all",price:checked("price")[0]||"all",materials:checked("material"),ingredients:checked("ingredient"),sort:sort?.value||"recommended"});
 const render=(reset=true)=>{if(reset)limit=24;const s=state();eligible=items.filter((x)=>(!s.query||x.search.includes(s.query))&&(!s.categories.length||s.categories.includes(x.category))&&(!s.brands.length||s.brands.includes(x.brand))&&(s.discount==="all"||bucket(x.discount,"discount")===s.discount)&&(s.price==="all"||bucket(x.price,"price")===s.price)&&(!s.materials.length||s.materials.some((v)=>x.materials.includes(v)))&&(!s.ingredients.length||s.ingredients.some((v)=>x.ingredients.includes(v))));
  eligible.sort((a,b)=>s.sort==="discount-desc"?b.discount-a.discount||a.recommended-b.recommended:s.sort==="checked-desc"?b.checked-a.checked||a.recommended-b.recommended:s.sort==="price-asc"?a.price-b.price||a.recommended-b.recommended:s.sort==="price-desc"?b.price-a.price||a.recommended-b.recommended:a.recommended-b.recommended);
  cards.forEach((card)=>{card.hidden=true;card.style.display="none";});eligible.slice(0,limit).forEach((x)=>{x.card.hidden=false;x.card.style.removeProperty("display");grid.append(x.card);});if(count)count.textContent=String(eligible.length);if(empty)empty.hidden=eligible.length>0;
  const active=s.categories.length+s.brands.length+(s.discount!=="all"?1:0)+(s.price!=="all"?1:0)+s.materials.length+s.ingredients.length+(s.query?1:0);if(badge){badge.textContent=String(active);badge.hidden=!active;}window.bulgaritamScheduleMasonry?.(grid);
 };
 const close=()=>{modal?.setAttribute("hidden","");toggle?.setAttribute("aria-expanded","false");document.documentElement.classList.remove("no-scroll");};
 toggle?.addEventListener("click",()=>{modal?.removeAttribute("hidden");toggle.setAttribute("aria-expanded","true");document.documentElement.classList.add("no-scroll");});modal?.querySelectorAll("[data-filters-close]").forEach((node)=>node.addEventListener("click",close));modal?.addEventListener("change",()=>render());document.querySelector("#applyFilters")?.addEventListener("click",()=>{render();close();});sort?.addEventListener("change",()=>render());document.querySelector("#dealSearchForm")?.addEventListener("submit",(event)=>{event.preventDefault();render();});search?.addEventListener("input",()=>render());
 const reset=()=>{if(search)search.value="";modal?.querySelectorAll<HTMLInputElement>('input[type="checkbox"]').forEach((input)=>input.checked=false);modal?.querySelectorAll<HTMLInputElement>('input[type="radio"][value="all"]').forEach((input)=>input.checked=true);render();};document.querySelector("#resetFilters")?.addEventListener("click",reset);document.querySelector("#emptyReset")?.addEventListener("click",reset);document.addEventListener("keydown",(event)=>{if(event.key==="Escape")close();});
 const sentinel=document.querySelector("#loadSentinel");if(sentinel)new IntersectionObserver((entries)=>{if(entries.some((entry)=>entry.isIntersecting)&&limit<eligible.length){limit+=24;render(false);}},{rootMargin:"500px"}).observe(sentinel);
 document.addEventListener("bulgaritam:deals-refreshed",()=>{cards=Array.from(grid.querySelectorAll<HTMLElement>("[data-masonry-card]"));items=mapItems();render();});render();
}
