import assert from "node:assert/strict";
import {deriveAnalyticsDomain,loadAllPages,loadDerivedAnalytics,productIdentity,validateDiscoveryData,type DiscoveryResultRow,type DiscoveryStateRow} from "../src/lib/analytics-derived";
import type {AnalyticsEvent} from "../src/lib/analytics";
let id=0;const event=(name:string,x:Partial<AnalyticsEvent>&{payload?:Record<string,unknown>}={}):AnalyticsEvent=>({id:++id,eventId:`e${id}`,event:name,at:new Date(`2026-09-02T10:00:${String(id).padStart(2,"0")}Z`),sessionId:"s1",journeyId:"v1",productId:"p1",productName:"One",productSlug:"one",brandId:"b1",brandName:"B1",brandSlug:"b1",category:"cat",subcategory:"sub",productType:"type",searchTerm:"soap",resultCount:2,collectionId:"",sourceContext:"",listContext:"",referrerDomain:"",utmSource:"",utmMedium:"",utmCampaign:"",searchId:"legacy-stale",pagePath:"/",pageType:"home",giftRecipient:"",giftOccasion:"",sequenceNumber:id,acquisitionChannel:"direct",landingPage:"/",discoveryStateId:"",searchRevision:1,payload:{},...x});
const state=(x:Partial<DiscoveryStateRow>={}):DiscoveryStateRow=>({discovery_state_id:"d1",occurred_at:"2026-09-02T10:00:00Z",anonymous_session_id:"s1",anonymous_journey_id:"v1",surface_type:"search_results",page_path:"/",search_id:"q1",query:"soap",result_count:2,...x});
const members:DiscoveryResultRow[]=[{discovery_state_id:"d1",entity_type:"product",product_id:"p1",brand_id:"b1",position:1},{discovery_state_id:"d1",entity_type:"product",product_id:"p2",brand_id:"b2",position:2}];
const ctx={source_surface:"search_results",source_discovery_state_id:"d1",source_search_id:"q1",source_position:1};
const domain=deriveAnalyticsDomain([
 event("product_impression",{payload:ctx}),event("product_impression",{eventId:"e1",payload:ctx}),
 event("view_product",{payload:{...ctx,view_stage:"selection_click",last_discovery_state_id:"old"}}),event("view_product",{payload:{...ctx,view_stage:"selection_click"}}),
 event("view_product",{payload:{view_stage:"page_load",source_surface:"product_page"}}),event("view_product",{payload:{view_stage:"page_load",source_surface:"product_page"}}),
 event("save_product",{payload:{source_surface:"product_page"}}),event("outbound_product_click",{payload:{source_surface:"product_page"}}),event("outbound_product_click",{payload:{source_surface:"product_page"}}),
], [state()],members);
assert.equal(domain.productExposures.length,1,"same event id is deduplicated");assert.equal(domain.productSelections.length,2);assert.equal(domain.productPageViews.length,2);assert.equal(domain.productOutboundIntents.length,2);
const f=domain.productFunnel.find(x=>x.product.productId==="p1")!;assert.equal(f.exposed.uniqueProductOpportunities,1);assert.equal(f.selected.uniqueProductOpportunities,1);assert.equal(f.pageViewed.eventCount,2);assert.equal(f.pageLoadPerSelection,1);assert.equal(f.considerationPerPageLoad,1);assert.equal(f.outboundPerExposure,1);assert.ok(!("conversionRate" in f));
assert.equal(domain.productSelections[0].searchId,"q1");assert.equal(domain.productSelections[0].influencedStateId,"old");
const stale=deriveAnalyticsDomain([event("view_product",{payload:{view_stage:"selection_click",source_surface:"related_products"}})],[state()],members);assert.equal(stale.productSelections[0].searchId,"","legacy event.searchId is not direct");assert.equal(stale.productSelections[0].sourceSurface,"related_products");

assert.notEqual(productIdentity({productId:"same",brandId:"a"})!.key,productIdentity({productId:"same",brandId:"b"})!.key);
const missing=deriveAnalyticsDomain([event("product_impression",{journeyId:"",sessionId:"",eventId:"m1"}),event("product_impression",{journeyId:"",sessionId:"",eventId:"m2"})]);assert.equal(missing.summary.qualifiedProductExposures,2);assert.equal(missing.productFunnel[0].exposed.uniqueVisitors,0);assert.equal(missing.productFunnel[0].exposed.uniqueProductOpportunities,0,"missing identities never collapse into one visitor opportunity");
const corrupt=deriveAnalyticsDomain([event("page_view",{sessionId:"shared",journeyId:"v1"}),event("page_view",{sessionId:"shared",journeyId:"v2"})]);assert.equal(corrupt.sessions[0].identityConflict,true);assert.equal(corrupt.sessions[0].visitorId,null);

const lookback=[event("view_product",{sessionId:"old",journeyId:"v1",at:new Date("2026-09-01T00:00:00Z"),payload:{view_stage:"page_load"}})];const returns=deriveAnalyticsDomain([event("view_product",{sessionId:"new",journeyId:"v1",at:new Date("2026-09-02T00:00:00Z"),payload:{view_stage:"page_load"}})],[],[],{periodStart:new Date("2026-09-02"),lookbackEvents:lookback});assert.equal(returns.summary.returningAnonymousVisitors,1);assert.equal(returns.summary.repeatProductInterest,1);assert.equal(returns.summary.repeatBrandInterest,1);
const sameSession=deriveAnalyticsDomain([event("view_product",{sessionId:"one",payload:{view_stage:"page_load"}}),event("view_product",{sessionId:"one",payload:{view_stage:"page_load"}})]);assert.equal(sameSession.summary.repeatProductInterest,0,"same-session reload is not cross-session return");

const searches=deriveAnalyticsDomain([], [state({discovery_state_id:"a1",anonymous_session_id:"a",search_id:"qa",query:"zero",result_count:0,occurred_at:"2026-09-02T10:00:00Z"}),state({discovery_state_id:"b1",anonymous_session_id:"b",search_id:"qb",query:"other",result_count:0,occurred_at:"2026-09-02T10:00:01Z"}),state({discovery_state_id:"a2",anonymous_session_id:"a",search_id:"qa2",query:"refined",result_count:0,occurred_at:"2026-09-02T10:00:02Z"}),state({discovery_state_id:"a3",anonymous_session_id:"a",search_id:"qa2",query:"refined",category:"cat",result_count:0,occurred_at:"2026-09-02T10:00:03Z"})],[]);const zero=searches.searchEpisodes.find(x=>x.query==="zero")!;assert.equal(zero.reformulationCandidate,true,"reformulation adjacency is session-local");assert.equal(searches.searchEpisodes.find(x=>x.searchId==="qa2")!.states.length,2,"filter states remain in one episode");

const brand=deriveAnalyticsDomain([event("brand_impression",{productId:"",productSlug:"",payload:{source_surface:"brand_directory",source_position:1}}),event("view_brand",{productId:"",productSlug:"",payload:{view_stage:"selection_click",source_surface:"brand_directory"}}),event("view_brand",{productId:"",productSlug:"",payload:{view_stage:"page_load",source_surface:"brand_page"}}),event("outbound_brand_click",{productId:"",productSlug:"",payload:{source_surface:"brand_page"}})]);assert.equal(brand.summary.brandQualifiedImpressions,1);assert.equal(brand.summary.brandSelections,1);assert.equal(brand.summary.brandPageViews,1);assert.equal(brand.summary.brandOutboundIntents,1);

const mismatch=validateDiscoveryData([state({result_count:2})],[members[0]]);assert.equal(mismatch.completeStates.length,0);assert.equal(mismatch.incompleteStates.length,1);const duplicate=validateDiscoveryData([state({result_count:2})],[members[0],{...members[1],position:1}]);assert.equal(duplicate.completeStates.length,0);
const big=Array.from({length:2001},(_,i)=>i);let pages=0;const loaded=await loadAllPages(async(from,to)=>{pages++;return big.slice(from,to+1)});assert.equal(loaded.length,2001);assert.equal(pages,3);let exactPages=0;assert.equal((await loadAllPages(async(f,t)=>{exactPages++;return big.slice(0,2000).slice(f,t+1)})).length,2000);assert.equal(exactPages,3,"exact 1000 boundary requests empty terminator page");
let calls:string[]=[];await loadDerivedAnalytics({loadEvents:async()=>{calls.push("events");return[]},loadLookbackEvents:async()=>{calls.push("lookback");return[]},loadDiscoveryStates:async()=>{calls.push("states");return[state()]},loadDiscoveryResults:async()=>{calls.push("results");return members}},new Date("2026-09-02"),new Date("2026-09-03"),new Date("2026-08-01"));assert.deepEqual(calls.sort(),["events","lookback","results","states"]);
console.log("Analytics V2 derived domain tests passed");
