import assert from "node:assert/strict";
import test from "node:test";
import { createConsumerDealsService, runConsumerDealsLkgSmokeTest } from "../src/lib/consumer-deals-api";

const deal=(id:number)=>({entity_type:"observed_product",entity_id:String(id),title:`Deal ${id}`,brand_id:1,brand:"Brand",image_url:"https://brand.test/x.jpg",current_price:49,regular_price:59,currency:"EUR",discount_percent:16.95,latest_checked_at:"2026-09-30T08:00:00Z",destination_type:"external",destination_url:`https://brand.test/${id}`,outbound_url:`https://brand.test/${id}`,materials:[],ingredients:[]});

test("data-only source changes appear after TTL without an Astro rebuild",async()=>{let rows=[deal(1)];const service=createConsumerDealsService({load:async()=>({deals:rows}),ttlMs:1,maxStaleMs:1000});const first=await service.get(new Date("2026-09-30T09:00:00.000Z"));rows=[deal(2)];const second=await service.get(new Date("2026-09-30T09:00:00.002Z"));assert.deepEqual(first.deals.map((x:any)=>x.entity_id),["1"]);assert.deepEqual(second.deals.map((x:any)=>x.entity_id),["2"]);const health=service.inspect(new Date("2026-09-30T09:00:00.002Z"));assert.equal(health.dealCount,1);assert.equal(health.lastRefreshStatus,"success");assert.equal(health.lastSuccessAt,Date.parse("2026-09-30T09:00:00.002Z"));});

test("last known good snapshot survives an upstream failure",async()=>{let fail=false;const service=createConsumerDealsService({load:async()=>{if(fail)throw new Error("upstream");return{deals:[deal(1)]}},ttlMs:1,maxStaleMs:1000});await service.get(new Date("2026-09-30T09:00:00.000Z"));fail=true;const stale=await service.get(new Date("2026-09-30T09:00:00.002Z"));assert.equal(stale.cache,"stale-if-error");assert.equal(stale.stale,true);assert.equal(stale.deals.length,1);const health=service.inspect(new Date("2026-09-30T09:00:00.002Z"));assert.equal(health.lastRefreshStatus,"stale_if_error");assert.match(health.lastError,/upstream/);assert.equal(health.lkgAgeMs,2);});

test("protected deployed smoke helper proves healthy to LKG transition without writes",async()=>{const result=await runConsumerDealsLkgSmokeTest(new Date("2026-09-30T09:00:00.000Z"),async()=>({deals:[deal(1)]}));assert.deepEqual(result,{passed:true,healthy_status:200,fallback_status:200,healthy_count:1,fallback_count:1,fallback_cache:"stale-if-error",fallback_stale:true,lkg_age_ms:1,generated_at_preserved:true,last_refresh_status:"stale_if_error"});});
